<?php

declare(strict_types=1);

namespace AlmaviaCX\Bundle\IbexaImportExport\Monolog;

use Symfony\Component\Console\Logger\ConsoleLogger;

class WorkflowConsoleLogger extends ConsoleLogger implements WorkflowLoggerInterface
{
    use WorkflowLoggerTrait;

    public function log($level, $message, array $context = [])
    {
        if ($this->itemIndex) {
            $context['item_index'] = $this->itemIndex;
            $message = "[{item_index}] {$message}";
        }
        parent::log($level, $message, $context); // TODO: Change the autogenerated stub
    }

    public function getRecords(): array
    {
        return [];
    }

    public function clearRecords(): void
    {
        return;
    }
}
