services:
    AlmaviaCX\Bundle\CaptchEtat\Logger\CaptchEtatLogger:
        arguments:
            $innerLogger: '@Psr\Log\LoggerInterface'

    AlmaviaCX\Bundle\CaptchEtat\Api\OauthGateway:
        arguments:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $logger: '@AlmaviaCX\Bundle\CaptchEtat\Logger\CaptchEtatLogger'
            $url: '%captchetat_oauth_url%'
            $clientId: '%captchetat_oauth_client_id%'
            $clientSecret: '%captchetat_oauth_client_secret%'
            $timeout: '%captchetat_timeout%'

    AlmaviaCX\Bundle\CaptchEtat\Api\Gateway:
        arguments:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $logger: '@AlmaviaCX\Bundle\CaptchEtat\Logger\CaptchEtatLogger'
            $oauthGateway: '@AlmaviaCX\Bundle\CaptchEtat\Api\OauthGateway'
            $url: '%captchetat_api_url%'
            $timeout: '%captchetat_timeout%'

    AlmaviaCX\Bundle\CaptchEtat\Challenge\ChallengeGenerator:
        arguments:
            $configResolver: '@Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface'
            $localeConverter: '@Ibexa\Core\MVC\Symfony\Locale\LocaleConverterInterface'
            $gateway: '@AlmaviaCX\Bundle\CaptchEtat\Api\Gateway'
            $translator: '@Symfony\Contracts\Translation\TranslatorInterface'
            $logger: '@AlmaviaCX\Bundle\CaptchEtat\Logger\CaptchEtatLogger'

    AlmaviaCX\Bundle\CaptchEtat\Challenge\ChallengeValidator:
        arguments:
            $gateway: '@AlmaviaCX\Bundle\CaptchEtat\Api\Gateway'

    AlmaviaCX\Bundle\CaptchEtat\Validator\CaptchEtatChallengeValidator:
        arguments:
            $challengeValidator: '@AlmaviaCX\Bundle\CaptchEtat\Challenge\ChallengeValidator'
            $translator: '@Symfony\Contracts\Translation\TranslatorInterface'
        tags:
            - validator.constraint_validator

    AlmaviaCX\Bundle\CaptchEtat\Form\Type\CaptchEtatType:
        lazy: true
        arguments:
            $challengeGenerator: '@AlmaviaCX\Bundle\CaptchEtat\Challenge\ChallengeGenerator'
        tags:
            - {name: 'form.type', alias: captchetat}

    AlmaviaCX\Bundle\CaptchEtatBundle\Controller\CaptchEtatController:
        arguments:
            $gateway: '@AlmaviaCX\Bundle\CaptchEtat\Api\Gateway'
        tags:
            - controller.service_arguments

#    AlmaviaCX\Bundle\CaptchEtat\FormBuilder\FieldType\Field\Mapper\ButtonFieldMapperDecorator:
#        decorates: Ibexa\FormBuilder\FieldType\Field\Mapper\ButtonFieldMapper
#        arguments:
#            $buttonFieldMapper: '@.inner'
