system:
    admin_group:
        fieldtypes:
            ibexa_richtext:
                toolbar:
                    group5:
                        buttons:
                            ibexaUploadFile:
                                priority: 25
