services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $translationHelper: '@Ibexa\Core\Helper\TranslationHelper'

    Novactive\EzMenuManager\Form\Type\FieldType\MenuItemFieldType: ~
    Novactive\EzMenuManager\Form\Type\FieldType\FieldValueTransformer: ~

    Novactive\EzMenuManager\Persistence\Legacy\Content\FieldValue\Converter\MenuItemConverter:
        tags:
            - {name: ibexa.field_type.storage.legacy.converter, alias: menuitem}
