services:
    Novactive\EzMenuManager\FieldType\MenuItem\ValueConverter:
        autowire: true

    Novactive\EzMenuManager\FieldType\MenuItem\Type:
        autowire: true
        parent: Ibexa\Core\FieldType\FieldType
        tags:
            - {name: ibexa.field_type, alias: menuitem}

    Novactive\EzMenuManager\FieldType\Mapper\MenuItemFormMapper:
        autowire: true
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: menuitem }
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: menuitem }

    Novactive\EzMenuManager\FieldType\MenuItem\MenuItemStorage:
        arguments:
            - '@Novactive\EzMenuManager\FieldType\MenuItem\MenuItemStorage\Gateway\DoctrineStorage'
        tags:
            - {name: ibexa.field_type.storage.external.handler, alias: menuitem}

    Novactive\EzMenuManager\FieldType\MenuItem\MenuItemStorage\Gateway\DoctrineStorage:
        autowire: true