services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\EzMenuManager\FieldType\MenuItem\SearchField:
        tags:
            - {name: ibexa.field_type.indexable, alias: menuitem}
