parameters:
    env(SAML_IDENTITY_PROVIDER_ENTITYID): ~
    env(SAML_IDENTITY_PROVIDER_LOGIN_URL): ~
    env(SAML_IDENTITY_PROVIDER_LOGIN_BINDING): ~
    env(SAML_IDENTITY_PROVIDER_LOGOUT_URL): ~
    env(SAML_IDENTITY_PROVIDER_LOGOUT_BINDING): ~
    env(SAML_IDENTITY_PROVIDER_X509_CERT): ~

    env(SAML_SERVICE_PROVIDER_URL): ~
    env(SAML_SERVICE_PROVIDER_NAMEID_FORMAT): ~

    env(SAML_SERVICE_PROVIDER_USER_GROUP_ID): ~

    almaviacx.saml.config.default.user_group_id: '%env(resolve:SAML_SERVICE_PROVIDER_USER_GROUP_ID)%'
