services:
    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\EnhancedImageStorage:
        parent: ezpublish.fieldType.ezimage.externalStorage
        tags:
            - {name: ezplatform.field_type.external_storage_handler, alias: enhancedimage}

    ezpublish.field_type.indexable.enhancedimage:
        parent: ezpublish.fieldType.indexable.ezimage
        class: eZ\Publish\Core\FieldType\Image\SearchField
        tags:
            - {name: ezplatform.field_type.indexable, alias: enhancedimage}

    ezpublish_rest.field_type_processor.enhancedimage:
        parent: ezpublish_rest.field_type_processor.ezimage
        tags:
            - { name: ibexa.rest.field_type.processor, alias: enhancedimage }

    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\Type:
        parent: ezpublish.fieldType.ezimage
        tags:
            - {name: ezplatform.field_type, alias: enhancedimage}

    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\ValueConverter:
        parent: ezpublish.fieldType.ezimage.converter
        tags:
            - {name: ezplatform.field_type.legacy_storage.converter, alias: enhancedimage}

    eZ\Publish\Core\FieldType\Image\Type: '@ezpublish.fieldType.ezimage'

    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\FormMapper:
        autoconfigure: true
        autowire: true
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: enhancedimage }
            - { name: ezplatform.field_type.form_mapper.value, fieldType: enhancedimage }
