services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZFastlyImageOptimizerBundle\Twig\Extension: ~
    Novactive\Bundle\eZFastlyImageOptimizerBundle\Core\AliasGenerator:
        arguments:
            - "@ibexa.field_type.ezimage.variation_service"
            - "@ibexa.config.resolver"
            - "@logger"
