services:
    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository:
        lazy: true
        arguments:
            $em: '@ibexa.doctrine.orm.entity_manager'
        tags:
            - doctrine.repository_service

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobService:
        arguments:
            $jobRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository'
            $jobRunner: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunnerInterface'
            $jobDebugger: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobDebugger'
            $configResolver: '@Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface'

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunnerInterface: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunner'
    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunner:
        arguments:
            $workflowExecutor: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowExecutor'
            $workflowRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry'
            $eventDispatcher: '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'
            $jobRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository'

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobDebugger:
        arguments:
            $workflowExecutor: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowExecutor'
            $workflowRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry'

