services:
    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository:
        lazy: true
        arguments:
            $em: '@ibexa.doctrine.orm.entity_manager'
        tags:
            - doctrine.repository_service

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobService:
        arguments:
            $jobRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository'
            $executionRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Execution\ExecutionRepository'
            $jobRunner: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunnerInterface'
            $jobDebugger: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobDebugger'
            $configResolver: '@Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface'
            $permissionResolver: '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunnerInterface: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunner'
    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunner:
        arguments:
            $executionRunner: '@AlmaviaCX\Bundle\IbexaImportExport\Execution\ExecutionRunner'
            $jobRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository'
            $executionRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Execution\ExecutionRepository'

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobDebugger:
        arguments:
            $workflowExecutor: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowExecutor'
            $workflowRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry'
