services:
    AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowConfigurationRepository:
        arguments:
            $entityManager: '@ibexa.doctrine.orm.entity_manager'

    AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowExecutor:
        arguments:
            $runConfigurationBuilder: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\RunConfigurationBuilder'

    AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry:
        arguments:
            $typeContainer: !abstract defined in AlmaviaCX\Bundle\IbexaImportExportBundle\DependencyInjection\CompilerPass\WorkflowPass
            $availableWorkflowServices: !abstract defined in AlmaviaCX\Bundle\IbexaImportExportBundle\DependencyInjection\CompilerPass\WorkflowPass

    AlmaviaCX\Bundle\IbexaImportExport\Workflow\AbstractWorkflow:
        lazy: true
        abstract: true

    AlmaviaCX\Bundle\IbexaImportExport\Workflow\RunConfigurationBuilder:
        arguments:
            $componentBuilder: '@AlmaviaCX\Bundle\IbexaImportExport\Component\ComponentBuilder'
