services:
    AlmaviaCX\Bundle\IbexaImportExport\MessageHandler\JobRunMessageHandler:
        arguments:
            $executionRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Execution\ExecutionRepository'
            $notificationSender: '@AlmaviaCX\Bundle\IbexaImportExport\Notification\NotificationSender'
            $messageBus: '@messenger.default_bus'
            $executionRunner: '@AlmaviaCX\Bundle\IbexaImportExport\Execution\ExecutionRunner'
        tags:
            - {name: 'messenger.message_handler', handles: AlmaviaCX\Bundle\IbexaImportExport\Message\JobStartMessage}
            - {name: 'messenger.message_handler', handles: AlmaviaCX\Bundle\IbexaImportExport\Message\JobResumeMessage}

    AlmaviaCX\Bundle\IbexaImportExport\Job\AsyncJobRunner:
        decorates: AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunner
        arguments:
            $jobRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository'
            $executionRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Execution\ExecutionRepository'
            $jobRunMessageHandler: '@AlmaviaCX\Bundle\IbexaImportExport\MessageHandler\JobRunMessageHandler'
            $originalRunner: '@AlmaviaCX\Bundle\IbexaImportExport\Job\AsyncJobRunner.inner'
