services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $entityManager: "@novaezrssfeed.doctrine.entity_manager"

  Novactive\EzRssFeedBundle\Controller\Admin\RssFeedController:
    tags: ['controller.service_arguments']

  Novactive\EzRssFeedBundle\PlatformAdminUI\EventListener\MainMenuBuilderListener:
    public: false
    arguments:
    - "@security.authorization_checker"
    tags:
    - { name: kernel.event_subscriber }

  Novactive\EzRssFeedBundle\PlatformAdminUI\Menu\RssEditRightSidebarBuilder:
    tags:
    - { name: knp_menu.menu_builder, method: build, alias: ibexa_admin_ui.menu_configure.rss_edit_sidebar_right }
