services:

    nova_ezrssfeed.ezadminui.component.stylesheets:
         parent: Ibexa\AdminUi\Component\TwigComponent
         public: false
         arguments:
            $template: '@@EzRssFeed/ezadminui/stylesheets.html.twig'
         tags:
             - { name: ibexa.admin_ui.component, group: 'stylesheet-head' }

    nova_ezrssfeed.ezadminui.component.javascripts:
         parent: Ibexa\AdminUi\Component\TwigComponent
         public: false
         arguments:
             $template: '@@EzRssFeed/ezadminui/javascripts.html.twig'
         tags:
             - { name: ibexa.admin_ui.component, group: 'script-body' }
