<?php

namespace MC\Bundle\PrivateContentAccessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrivateAccessEntityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PrivateAccessRepository extends EntityRepository
{
}
