services:
    ezmenumanager.ibexa.admin.component.stylesheets:
         parent: Ibexa\AdminUi\Component\TwigComponent
         arguments:
            $template: '@@EzMenuManager/themes/standard/ezadminui/stylesheets.html.twig'
         tags:
             - { name: ibexa.admin_ui.component, group: 'stylesheet-head' }
