language: php

php:
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction

script:
  - make tests