<?php

/**
 * NovaeZRssFeedBundle.
 *
 * @package   NovaeZRssFeedBundle
 *
 * @author    Novactive
 * @copyright 2018 Novactive
 * @license   https://github.com/Novactive/NovaeZRssFeedBundle/blob/master/LICENSE
 */

namespace Novactive\EzRssFeedBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Novactive\EzRssFeedBundle\Entity\RssFeeds;

/**
 * RssSitesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RssFeedSitesRepository extends EntityRepository
{
}
